### PR TITLE
Communal gambling

### PR DESCRIPTION
**Pull request by RyanO-K**
This PR enables 12 month tier 3 subscribers to start predictions in addition to the moderator ability to do so.

Line 284 of mod_commands.py can be altered to include 6moT3's/community managers by adding their role name to the list as well with no other changes.
This does allow the long term subs to flag the set nickname, which could be a pain.

Paying out and refunding predictions are still Mod exclusive.

### CODE REVIEW

**Comment by DarkView** [comment]
I nominate the Dev Contributor role for this feature too since I'm EU and can start a prediction every time on Ranked streams since they're at the perfect time for me. And Contributors are likely to understand how the commands work without any issues.

**Comment by DarkView** [comment]
Updated PR to use Config options instead of names to comply with #118

**Review by crscillitoe — CHANGES_REQUESTED** [review]
Please update this PR to send a message to a configurable "UserPredictionAuditChannel" ID. We need to be able to identify who has opened/closed a prediction in case of a malicious actor closing predictions to cause chaos (unlikely but necessary to track, also we could consider rewarding chatters for consistently running predictions in the future with such logging)

**Comment by DarkView** [comment]
Hijacking this PR with Streets express permission, as per "[...] away from home for the next week 💀- I need gambling. Hijack it.".

**Pull request merged**
